name: system_monitor
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cloud_firestore: ^3.1.5
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  firebase_core: ^1.10.6
  flutter:
    sdk: flutter
  get: ^4.6.1
  pie_chart: ^5.1.0
  shared_preferences: ^2.0.11
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/fonts/
  fonts:
    - family: RobotoM
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: RobotoB
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: RobotoR
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
