enum NetworkPath {
  LOGIN,
  REGISTER,
  GET_BOOKING_PRICE,
  POST_A_B_BOOKING,
  GET_PROFILE_DATA,
  FORGOT_PASSWORD,
  RESET_PASSWORD,
  CHECKOUT,
  POST_TO_THE_AIRPORT_BOOKING,
  POST_FROM_THE_AIRPORT_BOOKING,
  CHANGE_PASSWORD_UPDATE,
}
